# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 5",
   "iPhone 4s",
   "iPad Retina",
   "iPad Pro"
 ])

languages([
  "en-US"])

output_directory "./screenshots"
# Clears previous screenshots
clear_previous_screenshots

# Latest version of iOS
#ios_version '9.1'
